### ISSUE TITLE
Add recipe functionality

### ISSUE THREAD

**Issue by calmcgreggs** [stellaevat/wad2_team1a_pantry#42]

**Comment by stellaevat** [comment]
Issues to address:
(1) Reading in the newline characters from the text input for the method/steps (so they can be displayed as separate steps on the recipe);
(2) Category tags not saving properly for some reason;
(3) Turn difficulty into selection of the possible options rather than text input (probably need to add get_difficulties() method in the Recipe model so it can be called to retreive them)

**Comment by stellaevat** [comment]
Done
